### ISSUE TITLE
IllegalAccessError and ClassNotFoundException exceptions in integration process

### ISSUE THREAD

**Issue by mazitbehalf** [plaid/plaid-java#102]
Hi, 
I got two issues during integration process. I tried both version 2.1.6 which specified here and 2.2.0 which was used in your demo proj.

1. Gson version incompatible with our already used gson version causing IllegalAccessError exception (In your pom.xml I couldn't find gson version specified so I guess it used ours)

2018-01-08 15:50:08.161 ERROR 13152 --- [nio-8012-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter] with root cause

java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter
	at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:45)
	at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30)
	at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:297)
	at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:109)
	at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:162)

2.  ClassNotFoundException: okhttp3.internal.platform.Platform 
 
2018-01-08 15:54:08.377 ERROR 13249 --- [nio-8012-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform] with root cause

java.lang.ClassNotFoundException: okhttp3.internal.platform.Platform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:112)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:160)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)

Your assistance is appreciated.

**Comment by AshokRaj29** [comment]
Try to update the gson version, rebuilt and try again

**Comment by mazitbehalf** [comment]
I did it and got the second error ClassNotFoundException as described above

**Comment by AshokRaj29** [comment]
`		<dependency>
			<groupId>com.plaid</groupId>
			<artifactId>plaid-java</artifactId>
			<version>2.2.0</version>
		</dependency>

		<dependency>
			<groupId>com.squareup.retrofit2</groupId>
			<artifactId>retrofit</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.retrofit2</groupId>
			<artifactId>converter-gson</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>3.6.0</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>logging-interceptor</artifactId>
			<version>3.6.0</version>`

**Comment by mazitbehalf** [comment]
Thats works, thanks!
