### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by andrewsomesyoung** [plaid/plaid-java#115]
I updated to plaid-java version 2.2.2 and immediately started getting java.lang.StackOverflowErrors when calling transactionsGet. Looks like an issue with the json parsing? Reverting to version 2.1.6 made the errors go away.

java.lang.StackOverflowError
	at java.lang.Class.isArray(Native Method)
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:98)
	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72)
	at com.google.gson.reflect.TypeToken.get(TypeToken.java:296)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)

**Comment by mihahribar** [comment]
I have the same issue with version 3.0.0:

```
Caused by: java.lang.StackOverflowError
	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72)
	at com.google.gson.reflect.TypeToken.get(TypeToken.java:296)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:15)
	at com.plaid.client.internal.gson.ObjectSerializer.serialize(ObjectSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
```

Since I want to use the new version to get currency code support this issue needs to be resolved quickly.

**Comment by michaelckelly** [comment]
@andrewsomesyoung @mihahribar Thanks for flagging - we're investigating this and will follow up once we have more information. Apologies for the inconvenience!

**Comment by michaelckelly** [comment]
@andrewsomesyoung @mihahribar - Quick update, https://github.com/plaid/plaid-java/pull/117 should address this issue and we plan on releasing `3.0.1` with this change.

**Comment by mihahribar** [comment]
Just tested 3.0.1 and it works! Cheers @michaelckelly! 🍺
