### ISSUE TITLE
 java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by ariasf** [plaid/plaid-java#43]
So I'm trying to use plaid-java and when i try to create a  PlaidUserClient  to test operations with account i have connected via tartan I get the ERROR in the TITLE above, right after trying the code below.

`PlaidUserClient  client = PlaidClients.testUserClient(_MYCUSTOMERID, _MYCUSTOMERSECRET);`

Please let me know if you guys can point me in the right direction here. I'm coding in scala  using this java repo in Intellij15 windows machine.

**Comment by ariasf** [comment]
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:487)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:147)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:136)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:112)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
	at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:58)
	at com.plaid.client.http.ApacheHttpClientHttpDelegate.createDefault(ApacheHttpClientHttpDelegate.java:57)

**Comment by ariasf** [comment]
more log entries

**Comment by michaelckelly** [comment]
@ariasf - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
