### ISSUE TITLE
Android Integration Issue

### ISSUE THREAD

**Issue by wasim5390** [plaid/plaid-java#61]
### PlaidUserClient plaidUserClient = PlaidClients.testUserClient("test_id", "test_secret");

 java.lang.NoClassDefFoundError: org.apache.http.impl.client.HttpClientBuilder
                                                                          at com.plaid.client.PlaidClients.createHttpDelegate(PlaidClients.java:98)
                                                                          at com.plaid.client.PlaidClients.testUserClient(PlaidClients.java:24)
                                                                          at com.plaid.client.PlaidClients.testUserClient(PlaidClients.java:76)
                                                                          at com.plaid.client.PlaidClients.testUserClient(PlaidClients.java:71)

**Comment by fmontesino** [comment]
Which Android API version are you compiling with?
After 6.0 (API 23) they removed the apache HttpClient:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

Try adding this to your build.gradle file:
android {
    useLibrary 'org.apache.http.legacy'
}

Cheers!

**Comment by michaelckelly** [comment]
@wasim5390 @fmontesino  - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

Also, please note that including your Plaid client ID or secret in any application binary that is on an end-user device is not supported as that will compromise your API keys. Use [Plaid Link][3] instead.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
[3]: https://plaid.com/docs/api
