### ISSUE TITLE
PlaidClient cannot be used with @Inject in Wildfly

### ISSUE THREAD

**Issue by mihahribar** [plaid/plaid-java#71]
If I try and use `@Produces` to create instances of `PlaidClient` via the following code

```java
@Produces
@RequestScoped
public PlaidClient getPlaidClient()
{
	return PlaidClient.newBuilder()
			.clientIdAndSecret(CLIENT_ID, CLIENT_SECRET)
			.publicKey(PUBLIC_KEY)
			.sandboxBaseUrl()
			.build();
}
```

I get the following error pertaining to Weld:

```
Caused by: org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001437: Normal scoped bean class com.plaid.client.PlaidClient is not proxyable because the type is final or it contains a final method class com.plaid.client.PlaidClient - Producer Method [PlaidClient] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @RequestScoped public com.toshl.api.utils.Resources.getPlaidClient()].
 	at org.jboss.weld.util.Proxies.getUnproxyableClassException(Proxies.java:214)
 	at org.jboss.weld.util.Proxies.getUnproxyableTypeException(Proxies.java:178)
 	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
 	... 12 more
``` 

According to their [documentation](http://docs.jboss.org/weld/reference/latest/en-US/html/injection.html#_client_proxies) classes which are declared `final` or have a `final` method cannot be proxied.

Is there a reason `PlaidClient` is defined as `final`?

**Comment by jeeyoungk** [comment]
the `final` can be removed from the `PlaidClient`. It was there for coding convention because there's no need to subclass that class.

Not sure why this class needs to be proxied though. Does other workarounds specified in the documentation, including `change the type of the injection point to Instance<X>` not work for you?

**Comment by mihahribar** [comment]
Using `@Inject Instance<PlaidClient> plaidClient` is an option (one that I somehow missed). 

> Not sure why this class needs to be proxied though.

Is just a preference to have such clients managed by the server and for separation of concerns. Weld just does that by proxying.

**Comment by michaelckelly** [comment]
@mihahribar I'm going to go ahead and close this for now given the workaround! Please re-open if this is blocking you.

**Comment by tedwarner** [comment]
PlaidClient being final makes it impossible to mock out in tests without either reflection or writing a wrapper that forwards method calls to PlaidClient. Can you suggest an alternative that will allow me to test my code without instantiating the real PlaidClient?
