### ISSUE TITLE
java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter

### ISSUE THREAD

**Issue by Programmer0071** [plaid/plaid-java#97]
Response<ItemPublicTokenExchangeResponse> response = plaidClient.service()
		        		    .itemPublicTokenExchange(new ItemPublicTokenExchangeRequest("the_link_public_token")).execute();

		        		if (response.isSuccessful()) {
		        		  String accessToken = response.body().getAccessToken();
		        		  System.out.println(accessToken);
		        		}

error getting
-----------------
com.plaid.client.PlaidClient@6acdbdf5
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter
	at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:45)
	at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30)
	at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:297)
	at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:109)
	at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:162)
	at com.javainuse.SpringBatchApplication.main(SpringBatchApplication.java:34)

**Comment by michaelckelly** [comment]
@Programmer0071 - Are you still encountering this error? Do you have any other information about the request to help debug?

**Comment by Programmer0071** [comment]
Due to the mismatch Gson dependency i am having this issue, this is resolve now.......

**Comment by dopatraman** [comment]
I am running into this error on v 2.2.0 of the plaid-java sdk.
